### ISSUE TITLE
Font sizes not updating

### ISSUE THREAD

**Issue by secmann** [UniversalMailer/UniversalMailer#67] opened 2016-06-18 22:43 UTC
I have just downloaded the latest version (v3.0 build 10) and for some reason the outgoing font size I select via the 'Select' button is not being remembered when I try to update it and doesn't tie in with the font size displayed within the 'Default font' field.

Steps to replicate:
1. Click 'Universal Mailer icon and select the 'General' tab.
2. The ‘Default font:’ field displays ‘ArialMT - 10.0’
3. I click the ‘Select’ button to its right.
4. I choose a different font size, i.e. 12 from the fonts dialogue and close that window.
5. The Default font:’ field continues to display ‘ArialMT - 10.0’

![screen shot 2016-06-18 at 23 32 20](https://cloud.githubusercontent.com/assets/20019592/16174158/6a53a8aa-35ae-11e6-9b8b-4ebd502e99a7.png)

**Comment by UniversalMailer** [comment] 2016-08-09 19:28
Hi, it's this still an issue with the latest version (v3b14)?

**Comment by UniversalMailer** [comment] 2016-10-06 21:30
Closing this as a duplicate of #82

**Closed by UniversalMailer** 2016-10-06 21:30 UTC
